import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Providers from "./providers";
import Header from "@/components/side-panel";
import PreviewWindow from "@/components/preview-window";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#0f0f10] text-white`}
      >
        <Providers>
          <div className="flex h-screen">
            <div className="w-1/6 p-4 border-r bg-[#0a0a0a]">
              <Header />
            </div>
            <div className="flex-grow">{children}</div>
            <div className="w-1/3 p-4 border-l bg-[#0a0a0a]">
              <PreviewWindow />
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
